name: my_tasks_app
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  animate_do: ^4.2.0
  cupertino_icons: ^1.0.8
  equatable: ^2.0.7
  firebase_auth: ^6.0.0
  firebase_core: ^4.0.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  formz: ^0.8.0
  get_it: ^8.1.0
  go_router: ^16.0.0
  injectable: ^2.5.1
  intl: ^0.20.2

dev_dependencies:
  build_runner: ^2.6.0
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  injectable_generator: ^2.8.0

flutter:
  uses-material-design: true
